命令稿啟動於 2017年03月09日 (週四) 21時30分07秒
]0;yiju@yiju-VirtualBox: ~/lab1[01;32myiju@yiju-VirtualBox[00m:[01;34m~/lab1[00m$ g++ -o running.script [K[K[K[K[K[K[K[K[K[K[K[K[K[K[KA A.cpp
]0;yiju@yiju-VirtualBox: ~/lab1[01;32myiju@yiju-VirtualBox[00m:[01;34m~/lab1[00m$ ./A
22
22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1
]0;yiju@yiju-VirtualBox: ~/lab1[01;32myiju@yiju-VirtualBox[00m:[01;34m~/lab1[00m$ exit

命令稿已於 2017年03月09日 (週四) 21時30分28秒
 完成